'use strict';

const OL = 'https://covers.openlibrary.org/b/id/';
const AU = 'https://covers.openlibrary.org/a/olid/';

const BOOKS = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 14.99,
    category: "fiction",
    emoji: "📚",
    bg: "#fde8d8",
    cover: OL+'14351077-L.jpg',
    authorPhoto: AU+'OL18319A-L.jpg',
    description: "Set in the racially charged American South of the 1930s, this Pulitzer Prize-winning novel follows young Scout Finch as her father, attorney Atticus Finch, defends a Black man wrongly accused of a terrible crime. Through Scout's innocent eyes, Lee crafts a searing portrait of injustice, moral courage, and the loss of childhood innocence. Atticus remains one of literature's most beloved figures — a man who teaches his children to climb inside another's skin and walk around in it. Timeless, devastating, and deeply humane, this book has shaped the moral imagination of generations of readers around the world.",
    authorBio: "Harper Lee was born in 1926 in Monroeville, Alabama, a small town that would serve as the model for Maycomb in her novel. She studied law at the University of Alabama and moved to New York City to pursue writing. After years of effort and encouragement from her editor, she published her debut novel in 1960, which instantly became a cultural phenomenon. She won the Pulitzer Prize for Fiction in 1961. Lee remained famously reclusive for decades, rarely granting interviews. A second novel, Go Set a Watchman, was published in 2015. She passed away in 2016.",
    otherWorks: ["Go Set a Watchman (2015)"],
    recommendations: [3, 4, 9, 18],
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    price: 12.99,
    category: "fiction",
    emoji: "🔭",
    bg: "#dce8fd",
    cover: OL+'8745958-L.jpg',
    authorPhoto: AU+'OL22687A-L.jpg',
    description: "In a totalitarian future England, Winston Smith works for the Ministry of Truth, rewriting history to match the Party's ever-shifting version of reality. Under the omniscient gaze of Big Brother, even a private diary is an act of rebellion. When Winston falls in love with the free-spirited Julia and contacts a shadowy resistance movement, he dares to dream of a world without doublethink and Newspeak. Orwell's terrifying vision of surveillance, propaganda, and the erasure of individual thought has never felt more urgent. A foundational text of the twentieth century, 1984 is a warning that must be read and re-read in every generation.",
    authorBio: "George Orwell, born Eric Arthur Blair in 1903 in British India, was a novelist, essayist, and fierce critic of totalitarianism. He was educated at Eton before serving with the Imperial Police in Burma, an experience that deepened his disdain for imperialism. He fought in the Spanish Civil War, where he was shot through the throat. His experiences fuelled works of searing political clarity. Best known for Animal Farm and 1984, he also wrote celebrated essays on language, politics, and culture. Orwell died of tuberculosis in 1950, just months after completing his masterpiece.",
    otherWorks: ["Animal Farm (1945)", "Homage to Catalonia (1938)", "Down and Out in Paris and London (1933)", "Burmese Days (1934)"],
    recommendations: [5, 7, 6, 3],
  },
  {
    id: 3,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 11.99,
    category: "fiction",
    emoji: "✨",
    bg: "#fdfde0",
    cover: OL+'10590366-L.jpg',
    authorPhoto: AU+'OL18218A-L.jpg',
    description: "Narrated by the observant Nick Carraway, this dazzling Jazz Age novel follows the mysterious millionaire Jay Gatsby and his obsessive pursuit of Daisy Buchanan, the golden girl he lost years before. Through lavish Long Island parties and the ash-grey Valley of Ashes, Fitzgerald illuminates the hollowness beneath the American Dream's glittering surface. No novel captures the recklessness and yearning of the 1920s with such lyrical precision. Gatsby's doomed romanticism — reaching forever toward that green light across the water — remains one of literature's most indelible images, a meditation on hope, illusion, and the impossibility of recapturing the past.",
    authorBio: "F. Scott Fitzgerald was born in 1896 in St. Paul, Minnesota, and became the defining voice of the Jazz Age. He studied at Princeton before dropping out to enlist during World War I, where he began his first novel. His marriage to the vivacious Zelda Sayre epitomised the glamour and instability of the era he chronicled. Though The Great Gatsby received mixed reviews on publication, it is now considered the Great American Novel. Fitzgerald struggled with alcoholism and financial pressures throughout his career. He died in 1940, largely forgotten, while working on The Last Tycoon.",
    otherWorks: ["Tender Is the Night (1934)", "This Side of Paradise (1920)", "The Beautiful and Damned (1922)"],
    recommendations: [1, 4, 2, 17],
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 10.99,
    category: "fiction",
    emoji: "💌",
    bg: "#fde0e8",
    cover: OL+'13148521-L.jpg',
    authorPhoto: AU+'OL21594A-L.jpg',
    description: "When the charming but proud Mr. Darcy enters the life of the witty Elizabeth Bennet, their mutual prejudices set the stage for one of literature's greatest love stories. Austen's razor-sharp social comedy skewers the marriage-obsessed gentry of Regency England with warm irony and perfect comic timing. Mrs. Bennet's scheming, Mr. Collins's pomposity, and Wickham's easy charm are observed with devastating precision, while Elizabeth and Darcy gradually dismantle their misconceptions in scenes of delicious tension. Two centuries after publication, Pride and Prejudice remains the definitive novel of self-knowledge and love — a book that rewards every re-reading with new pleasures.",
    authorBio: "Jane Austen was born in 1775 in Steventon, Hampshire, the seventh of eight children. Largely self-educated, she began writing fiction as a teenager, producing brilliant parodies and sketches. Despite never marrying, she wrote with unmatched insight into love, money, and social convention. Her six completed novels — including Sense and Sensibility, Emma, and Persuasion — were all published during or just after her lifetime. Austen received little public recognition in her day, publishing anonymously. She died in 1817 at just 41, but her reputation has grown continuously, cementing her as one of the greatest novelists in the English language.",
    otherWorks: ["Sense and Sensibility (1811)", "Emma (1815)", "Persuasion (1817)", "Northanger Abbey (1817)", "Mansfield Park (1814)"],
    recommendations: [1, 3, 11, 17],
  },
  {
    id: 5,
    title: "Dune",
    author: "Frank Herbert",
    price: 16.99,
    category: "sci-fi",
    emoji: "🏜️",
    bg: "#fdf3d0",
    cover: OL+'11481354-L.jpg',
    authorPhoto: AU+'OL25791A-L.jpg',
    description: "On the desert planet Arrakis — the only source of the universe's most precious substance, the spice mélange — young Paul Atreides is thrust into a deadly political struggle that will transform him into a messianic figure. Herbert's monumental novel weaves together ecology, religion, politics, and destiny into a tapestry of breathtaking scope and detail. The sandworms, the Fremen, the Bene Gesserit, and the rival houses of the Imperium form a world-building achievement unmatched in science fiction. More than a saga of adventure, Dune is a profound meditation on the dangers of hero-worship and the fragility of civilisation — and the greatest science fiction novel ever written.",
    authorBio: "Frank Herbert was born in 1920 in Tacoma, Washington. He worked as a journalist, photographer, and oyster diver before achieving fame with Dune, published in 1965 after being rejected by more than twenty publishers. Inspired by an article on Oregon sand dunes, Herbert spent years researching ecology, religion, and politics to build Arrakis. The novel won both the Hugo and Nebula awards. Herbert continued the Dune saga across five sequels, exploring the long-term consequences of his universe with philosophical rigour. He died in 1986 of pancreatic cancer, leaving behind an unfinished seventh book.",
    otherWorks: ["Dune Messiah (1969)", "Children of Dune (1976)", "God Emperor of Dune (1981)", "The White Plague (1982)"],
    recommendations: [2, 6, 7, 8],
  },
  {
    id: 6,
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    price: 13.99,
    category: "sci-fi",
    emoji: "🚀",
    bg: "#d0f0fd",
    cover: OL+'11972784-L.jpg',
    authorPhoto: AU+'OL25698A-L.jpg',
    description: "Moments before the Earth is demolished to make way for a hyperspace bypass, Arthur Dent is whisked into the cosmos by his friend Ford Prefect, a researcher for the eponymous Hitchhiker's Guide. What follows is a gloriously absurdist tour of the universe — from the restaurant at the end of everything to the planet where the question to Life, the Universe, and Everything was computed over ten million years (the answer, disappointingly, is 42). Adams's wit is breathtaking in its precision and invention, skewering bureaucracy, philosophy, and human self-importance with equal glee. Endlessly quotable and genuinely hilarious, this book made comedy science fiction a serious literary art form.",
    authorBio: "Douglas Adams was born in 1952 in Cambridge, England. He studied English literature at St John's College, Cambridge, where he briefly met the Monty Python team. He went on to write for radio, television, and the stage before The Hitchhiker's Guide — originally a BBC Radio 4 series — became an international publishing phenomenon. A committed environmentalist, he co-authored Last Chance to See about endangered species. Adams was famous for his missed deadlines and self-described love of the 'whooshing' sound they made as they passed. He died suddenly of a heart attack in 2001 at the age of 49.",
    otherWorks: ["The Restaurant at the End of the Universe (1980)", "Life, the Universe and Everything (1982)", "So Long, and Thanks for All the Fish (1984)", "Mostly Harmless (1992)", "Dirk Gently's Holistic Detective Agency (1987)"],
    recommendations: [5, 7, 8, 2],
  },
  {
    id: 7,
    title: "Neuromancer",
    author: "William Gibson",
    price: 13.49,
    category: "sci-fi",
    emoji: "💾",
    bg: "#d0fde0",
    cover: OL+'283860-L.jpg',
    authorPhoto: AU+'OL26551A-L.jpg',
    description: "Henry Case is a burned-out hacker hired by a mysterious employer for one last run in cyberspace — a glittering consensual hallucination of data that Gibson named the Matrix. In a future of neon-drenched sprawls, black-market implants, and corporate dystopia, Case teams up with the lethal street samurai Molly Millions in a heist that reaches toward artificial intelligence and beyond. Gibson invented the language of the internet age before the internet existed, coining 'cyberspace' and shaping how a generation imagines digital life. Neuromancer won the Hugo, Nebula, and Philip K. Dick awards in the same year — a feat never repeated — and remains the founding text of cyberpunk.",
    authorBio: "William Gibson was born in 1948 in Conway, South Carolina. He moved to Canada to avoid the Vietnam draft and settled in Vancouver. A self-described slow reader with a passion for junk culture, he found science fiction as an escape and began selling stories in the late 1970s. Neuromancer, his debut novel, was published in 1984 and redefined the genre. Gibson has since explored technology's intersection with culture, identity, and power in novels including the Sprawl trilogy, the Bridge trilogy, and the Bigend trilogy. He continues to write and is regarded as one of the most influential living authors.",
    otherWorks: ["Count Zero (1986)", "Mona Lisa Overdrive (1988)", "Virtual Light (1993)", "Pattern Recognition (2003)", "Agency (2020)"],
    recommendations: [2, 5, 8, 6],
  },
  {
    id: 8,
    title: "Ender's Game",
    author: "Orson Scott Card",
    price: 14.49,
    category: "sci-fi",
    emoji: "🛸",
    bg: "#e0d0fd",
    cover: OL+'12996033-L.jpg',
    authorPhoto: AU+'OL25816A-L.jpg',
    description: "Six-year-old Andrew 'Ender' Wiggin is recruited to Battle School, a zero-gravity military academy orbiting Earth where children are trained to fight a coming alien invasion. Gifted beyond measure, manipulated by commanders who see him as humanity's last hope, Ender navigates brutal rivalries and impossible games while his siblings wage a different kind of war back on Earth. Card's novel is a riveting exploration of genius, isolation, and the moral cost of warfare — asking whether the ends can ever justify the means when the means involve a child. One of the bestselling science fiction novels of all time, it rewards readers of every age with fresh insight.",
    authorBio: "Orson Scott Card was born in 1951 in Richland, Washington. He studied at Brigham Young University and the University of Utah, and began his career writing plays and short fiction for science fiction magazines. Ender's Game began as a short story in 1977 before becoming a novel in 1985, winning both the Hugo and Nebula awards — an achievement he repeated the following year with the sequel Speaker for the Dead. Card has been prolific across science fiction, fantasy, and historical fiction. He is also a playwright and taught creative writing at Southern Virginia University for many years.",
    otherWorks: ["Speaker for the Dead (1986)", "Xenocide (1991)", "Ender's Shadow (1999)", "Pathfinder (2010)"],
    recommendations: [5, 6, 7, 2],
  },
  {
    id: 9,
    title: "Gone Girl",
    author: "Gillian Flynn",
    price: 13.99,
    category: "mystery",
    emoji: "🔍",
    bg: "#fde0e0",
    cover: OL+'8368314-L.jpg',
    authorPhoto: AU+'OL5715971A-L.jpg',
    description: "On the morning of their fifth wedding anniversary, Amy Dunne disappears, and all evidence points to her husband Nick. Told in alternating narratives — Nick's anxious present and Amy's diary entries from the past — Gone Girl is a razor-sharp dissection of marriage, media, and the stories we tell ourselves and others. Flynn subverts thriller conventions at every turn, delivering plot twists that genuinely shock while exploring the performance of identity in a marriage grown toxic. Dark, witty, and deeply unsettling, this novel announced Flynn as a master of the domestic thriller and became a cultural phenomenon that launched countless imitators — none quite matching its cold, brilliant audacity.",
    authorBio: "Gillian Flynn was born in 1971 in Kansas City, Missouri. She studied English and journalism at the University of Kansas and Northwestern University, then spent more than a decade as an entertainment journalist at Entertainment Weekly. Her debut novel Sharp Objects drew on a dark, unflinching view of small-town America and female violence. Gone Girl, her third novel, became a number-one bestseller and was adapted into a critically acclaimed film directed by David Fincher in 2014. Flynn wrote the screenplay herself. She continues to write fiction and has also worked as a screenwriter and producer in television.",
    otherWorks: ["Sharp Objects (2006)", "Dark Places (2009)"],
    recommendations: [10, 11, 1, 3],
  },
  {
    id: 10,
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    price: 15.99,
    category: "mystery",
    emoji: "🐉",
    bg: "#e0fde0",
    cover: OL+'10567897-L.jpg',
    authorPhoto: AU+'OL5922906A-L.jpg',
    description: "Disgraced financial journalist Mikael Blomkvist is hired by a reclusive industrialist to investigate the decades-old disappearance of his niece from a family estate steeped in dark secrets. Meanwhile, the brilliant, tattooed hacker Lisbeth Salander — a ward of the state whose fierce intelligence is matched only by her capacity for vengeance — becomes an unlikely ally. Larsson's Scandinavian thriller grips from the opening pages and doesn't release until the stunning final act. Rich with social commentary on violence against women and corporate corruption, and driven by two of crime fiction's most compelling protagonists, this novel launched a global phenomenon and permanently altered the thriller landscape.",
    authorBio: "Stieg Larsson was born in 1954 in Skellefteå, Sweden. He was a journalist and editor who spent decades investigating far-right extremism for the Swedish magazine Expo, which he co-founded. He wrote the Millennium trilogy — three thrillers featuring Lisbeth Salander — in his spare time, completing all three before his sudden death from a heart attack in 2004, aged just 50, before any were published. The novels were posthumously released to worldwide acclaim, selling over 100 million copies. A fourth book in the series, The Girl in the Spider's Web, was written by David Lagercrantz with the approval of Larsson's estate.",
    otherWorks: ["The Girl Who Played with Fire (2006)", "The Girl Who Kicked the Hornets' Nest (2007)"],
    recommendations: [9, 11, 7, 2],
  },
  {
    id: 11,
    title: "Big Little Lies",
    author: "Liane Moriarty",
    price: 12.99,
    category: "mystery",
    emoji: "🤫",
    bg: "#fde8fd",
    cover: OL+'7352410-L.jpg',
    authorPhoto: AU+'OL6962779A-L.jpg',
    description: "At a primary school trivia night in a wealthy Sydney suburb, someone is murdered. The question is who — and why. Told through police interviews, gossip, and shifting perspectives, Big Little Lies weaves together the lives of three women: the magnetic Madeline, the serene Celeste, and the newcomer Jane, who carries a secret that threatens to unravel everything. Moriarty crafts a novel that is simultaneously sharp social comedy and devastating thriller, exploring domestic violence, bullying, and the dangerous fictions of a perfect life with wit and compassion. The HBO adaptation starring Reese Witherspoon and Nicole Kidman introduced Moriarty's work to millions of new readers worldwide.",
    authorBio: "Liane Moriarty was born in 1966 in Sydney, Australia, the fourth of six siblings including her novelist sister Jaclyn Moriarty. She studied English and worked in advertising and marketing before turning to fiction full-time. Her novels are known for combining dark subject matter with warm humour and brilliantly observed characterisation. Big Little Lies became her international breakthrough, topping bestseller lists in multiple countries. The HBO adaptation won multiple Emmy and Golden Globe awards. Moriarty has also written several novels for younger readers. She lives in Sydney and is one of Australia's most beloved authors.",
    otherWorks: ["The Husband's Secret (2013)", "Nine Perfect Strangers (2018)", "Truly Madly Guilty (2016)", "What Alice Forgot (2009)"],
    recommendations: [9, 10, 4, 1],
  },
  {
    id: 12,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: 17.99,
    category: "non-fiction",
    emoji: "🧠",
    bg: "#fdf0d0",
    cover: OL+'8634250-L.jpg',
    authorPhoto: AU+'OL7219060A-L.jpg',
    description: "How did Homo sapiens come to dominate the Earth? Harari's sweeping history of humankind — from the cognitive revolution of 70,000 years ago to the present — answers this question with breathtaking breadth and intellectual daring. He argues that what separates us from other animals is the unique ability to believe in shared fictions: money, nations, religions, corporations. This capacity for collective imagination built empires, launched scientific revolutions, and now risks creating gods from mere mortals. Sapiens is one of those rare books that genuinely changes how you see everything — history, economics, religion, and the future of our species. Challenging, provocative, and impossible to put down.",
    authorBio: "Yuval Noah Harari was born in 1976 in Kiryat Ata, Israel. He earned his doctorate in medieval military history from Oxford University and is a professor at the Hebrew University of Jerusalem. Sapiens began as a series of introductory lectures and was first published in Hebrew in 2011 before its English translation became a global phenomenon. His subsequent books Homo Deus and 21 Lessons for the 21st Century have continued to explore humanity's past, present, and future with characteristic scope and provocation. A committed vegan and meditator, Harari attributes his clarity of thought to his daily two-hour Vipassana meditation practice.",
    otherWorks: ["Homo Deus (2015)", "21 Lessons for the 21st Century (2018)", "Unstoppable Us (2022)"],
    recommendations: [14, 13, 15, 16],
  },
  {
    id: 13,
    title: "Atomic Habits",
    author: "James Clear",
    price: 16.99,
    category: "non-fiction",
    emoji: "⚛️",
    bg: "#d8fde8",
    cover: OL+'12539702-L.jpg',
    authorPhoto: AU+'OL7538312A-L.jpg',
    description: "Tiny changes, remarkable results. James Clear's bestselling guide to behaviour change argues that the key to building good habits and breaking bad ones lies not in motivation or willpower, but in the small adjustments we make to our systems and environment. Drawing on research in psychology, neuroscience, and biology, Clear presents a clear four-step framework — cue, craving, response, reward — and practical strategies for making any behaviour easier or harder. Whether you want to exercise more, quit smoking, or write a novel, Atomic Habits provides the science-backed roadmap. With over fifteen million copies sold, it is the definitive modern guide to the art of self-improvement.",
    authorBio: "James Clear was born in 1986 and grew up in Hamilton, Ohio. While playing baseball at Denison University, he was struck in the face by a bat, suffering a near-fatal injury. His recovery became a years-long education in habits, recovery, and marginal gains. He began writing about habits and decision-making on his website in 2012, building an audience of millions. Atomic Habits, published in 2018, became one of the fastest-selling books of the decade and has spent years on the New York Times bestseller list. Clear speaks at Fortune 500 companies and continues to write his popular weekly newsletter on habits and decision-making.",
    otherWorks: [],
    recommendations: [14, 15, 12, 16],
  },
  {
    id: 14,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: 16.49,
    category: "non-fiction",
    emoji: "🧩",
    bg: "#d8e8fd",
    cover: OL+'13290711-L.jpg',
    authorPhoto: AU+'OL1515539A-L.jpg',
    description: "Nobel laureate Daniel Kahneman takes readers on a tour of the human mind through the lens of his decades of research with Amos Tversky. The central thesis is elegant: we have two modes of thought — System 1, which is fast, intuitive, and emotional; and System 2, which is slow, deliberate, and logical. Understanding how and when each system operates, and the systematic biases and errors they produce, is essential for making better decisions in every area of life. From loss aversion to the planning fallacy, from anchoring to overconfidence, Kahneman illuminates the hidden architecture of our choices. A masterwork of popular science that is indispensable for anyone seeking to understand the human mind.",
    authorBio: "Daniel Kahneman was born in 1934 in Tel Aviv and spent his childhood in France, narrowly surviving the Nazi occupation. He studied psychology at the Hebrew University of Jerusalem and earned his PhD from Berkeley. With his late partner Amos Tversky, he developed prospect theory and the field of behavioural economics, revolutionising our understanding of human decision-making. In 2002 he was awarded the Nobel Memorial Prize in Economic Sciences — unusual for a psychologist. Kahneman spent much of his career at Princeton University's Woodrow Wilson School. He passed away in 2024, leaving behind a profound scientific legacy.",
    otherWorks: ["Noise: A Flaw in Human Judgment (2021)"],
    recommendations: [12, 13, 15, 16],
  },
  {
    id: 15,
    title: "The Power of Now",
    author: "Eckhart Tolle",
    price: 14.99,
    category: "non-fiction",
    emoji: "🌿",
    bg: "#e8fdd8",
    cover: OL+'551262-L.jpg',
    authorPhoto: AU+'OL2634677A-L.jpg',
    description: "At 29, Eckhart Tolle woke one morning in a state of bliss so profound it transformed his understanding of consciousness. The result, distilled over years of meditation and teaching, is a guide to awakening from the suffering caused by compulsive thinking. Tolle's central message is radical in its simplicity: the present moment is all we ever have, and accessing it fully is the path to freedom from anxiety and pain. Written as a dialogue between teacher and questioner, The Power of Now draws on Christianity, Buddhism, and ancient wisdom without being bound to any tradition. With millions of copies sold worldwide and Oprah Winfrey's endorsement, it remains a cornerstone of modern spiritual literature.",
    authorBio: "Eckhart Tolle was born Ulrich Leonard Tolle in 1948 in Lünen, Germany. After a miserable childhood, he studied literature, philosophy, and languages at the University of London and Cambridge. At 29 he underwent a sudden spiritual transformation that he later described in The Power of Now. He spent several years as a vagrant, in a state of inner peace, before beginning to teach. Self-published initially, The Power of Now caught Oprah Winfrey's attention and became a global phenomenon. Tolle now lives in Vancouver and is regarded as one of the most influential spiritual teachers of our time.",
    otherWorks: ["A New Earth (2005)", "Stillness Speaks (2003)", "Guardians of Being (2009)"],
    recommendations: [13, 14, 12, 16],
  },
  {
    id: 16,
    title: "Steve Jobs",
    author: "Walter Isaacson",
    price: 18.99,
    category: "biography",
    emoji: "🍎",
    bg: "#fde8d0",
    cover: OL+'12374726-L.jpg',
    authorPhoto: AU+'OL1513789A-L.jpg',
    description: "Based on more than forty interviews with Steve Jobs conducted over two years — as well as conversations with family members, friends, adversaries, and colleagues — this is the exclusive biography of the co-founder of Apple. Isaacson portrays a man of extraordinary creativity and vision who could also be petty, cruel, and oblivious to those around him. Jobs's story is the story of Silicon Valley's rise, of the digital revolution, and of what it means to lead with relentless perfectionism. From the garage in Los Altos to the glass Apple Stores and beyond, this is a biography about the intersection of technology and the humanities that Jobs considered his greatest calling.",
    authorBio: "Walter Isaacson was born in 1952 in New Orleans and educated at Tulane University and Oxford, where he studied as a Rhodes Scholar. He worked for Time magazine for many years, eventually becoming its managing editor, and later served as chairman of CNN. His biographies of major historical figures — including Benjamin Franklin, Albert Einstein, Leonardo da Vinci, and Jennifer Doudna — have all become bestsellers. Steve Jobs, published in 2011 two weeks after Jobs's death, sold more than a million copies in its first week. Isaacson is currently a professor of history at Tulane and a regular contributor on technology and leadership.",
    otherWorks: ["Einstein: His Life and Universe (2007)", "Benjamin Franklin: An American Life (2003)", "Leonardo da Vinci (2017)", "The Code Breaker (2021)"],
    recommendations: [17, 18, 12, 14],
  },
  {
    id: 17,
    title: "Becoming",
    author: "Michelle Obama",
    price: 17.99,
    category: "biography",
    emoji: "🌟",
    bg: "#ffd8e8",
    cover: OL+'8824664-L.jpg',
    authorPhoto: AU+'OL6950613A-L.jpg',
    description: "In her memoir, Michelle Obama invites readers into her world, beginning with her Chicago South Side childhood through her years at Princeton and Harvard Law School, her early legal career, and the whirlwind of life in the White House. Written with remarkable candour and warmth, Becoming chronicles her journey from a working-class family to becoming the first Black First Lady of the United States. She writes honestly about marriage, motherhood, the pressures of public life, and the moments of doubt and joy that shaped her. A generous, inspiring, and beautifully written book, Becoming became the bestselling memoir in history, selling over fifteen million copies worldwide.",
    authorBio: "Michelle Obama was born in 1964 on the South Side of Chicago to a close-knit working-class family. She graduated from Princeton University in 1985 and Harvard Law School in 1988, where she specialised in marketing and intellectual property law. She met Barack Obama at a Chicago law firm where she was assigned as his adviser. After leaving the White House in 2017, she launched the Obama Foundation's Girls Opportunity Alliance and has been a prominent advocate for education, healthy eating, and voting rights. Becoming, published in 2018, broke all records for memoir sales and was followed by The Light We Carry in 2022.",
    otherWorks: ["The Light We Carry (2022)"],
    recommendations: [16, 18, 12, 1],
  },
  {
    id: 18,
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    price: 11.99,
    category: "biography",
    emoji: "📖",
    bg: "#fdfad8",
    cover: OL+'13526331-L.jpg',
    authorPhoto: AU+'OL111551A-L.jpg',
    description: "From June 1942 until August 1944, Anne Frank kept a diary while hiding with her family in a sealed-off apartment in Amsterdam. She wrote with the freshness, humour, and acute self-awareness of an extraordinary young mind — recording her fears, her dreams, her first love, and her fierce hope for the future. Discovered in the rubble after the Franks were arrested and deported to concentration camps, this diary was rescued and published by her father Otto, the sole survivor of the family. It has since sold over 35 million copies in over 70 languages. A testament to the resilience of the human spirit and an indictment of human cruelty, it remains one of the most important books ever written.",
    authorBio: "Anne Frank was born Annelies Marie Frank on 12 June 1929 in Frankfurt, Germany. As the Nazis rose to power, her family fled to Amsterdam. When Germany occupied the Netherlands, the Frank family went into hiding in July 1942 in a concealed annex above her father's business. Anne received a diary for her thirteenth birthday and began chronicling life in hiding with remarkable clarity and insight. In August 1944 the family was betrayed and arrested. Anne died of typhus in Bergen-Belsen concentration camp in February 1945, aged 15. Her father Otto, the only survivor, published her diary in 1947.",
    otherWorks: ["Tales from the Secret Annex (1949)"],
    recommendations: [16, 17, 1, 12],
  },
];
